// Packages
const inquirer = require("inquirer");
const fs = require("fs");

//shape library
const {Square, Circle, Triangle } = require("./lib/shapes");

// run user promptsg
promptUser();

// Function writes the SVG file using user answers from inquirer prompts
function writeToFile(fileName, answers) {
    let svgString = "";
    // Logo size
    svgString =
      '<svg version="1.1" width="300" height="200" xmlns="http://www.w3.org/2000/svg">';
    // text placed inside shape
    svgString += "<g>";
    // Input shape selection into SVG
    svgString += `${answers.shape}`;

  // if/else shape selection generated by user input 
  let shapeChoice;
  if (answers.shape === "Triangle") {
    shapeChoice = new Triangle();
    svgString += `<polygon points="150, 18 244, 182 56, 182" fill="${answers.shapeBackgroundColor}"/>`;
  } else if (answers.shape === "Square") {
    shapeChoice = new Square();
    svgString += `<rect x="73" y="40" width="160" height="160" fill="${answers.shapeBackgroundColor}"/>`;
  } else {
    shapeChoice = new Circle();
    svgString += `<circle cx="150" cy="115" r="80" fill="${answers.shapeBackgroundColor}"/>`;
  }
  
// text design 
  svgString += `<text x="150" y="130" text-anchor="middle" font-size="40" fill="${answers.textColor}">${answers.text}</text>`;
  svgString += "</g>";
  svgString += "</svg>";

 //fs file generation or error log 
 fs.writeFile(fileName, svgString, (err) => {
    err ? console.log(err) : console.log("Generated logo.svg");
  });
}

// List of user prompts
function promptUser() {
    inquirer
      .prompt([
       
        {
          type: "input",
          message:
            "Please select up to 3 characters for your logo.",
          name: "text",
        },
        // Text color prompt
        {
          type: "input",
          message:
            "Please select a color for your text.",
          name: "textColor",
        },
        // Shape choice prompt
        {
          type: "list",
          message: "Please select a background shape.",
          choices: ["Triangle", "Square", "Circle"],
          name: "shape",
        },
        // Shape color prompt
        {
          type: "input",
          message:
            "Please select a color for your background shape",
          name: "shapeColor",
        },
      ])
      // write to file or throw error if user did not follow prompts correctly
      .then((answers) => {
        if (answers.text.length > 3) {
          console.log("Please limit your text to 3 characters");
          promptUser();
        } else {
          writeToFile("logo.svg", answers);
        }
      });
  }


